// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.extjstest.domain.security;

import com.itg.extjstest.domain.security.AclEntry;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AclEntry_Roo_Configurable {
    
    declare @type: AclEntry: @Configurable;
    
}
