// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.extjstest.domain.security;

import com.itg.extjstest.domain.security.AclClass;
import com.itg.extjstest.domain.security.AclObjectIdentity;
import com.itg.extjstest.domain.security.AclSid;

privileged aspect AclObjectIdentity_Roo_JavaBean {
    

    
}
