// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.extjstest.domain.security;

import com.itg.extjstest.domain.security.UserDetail;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect UserDetail_Roo_Finder {
    

    
}
