// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.extjstest.domain;

import com.itg.extjstest.domain.Contract;
import com.itg.extjstest.domain.ContractItem;
import com.itg.extjstest.domain.ContractType;
import com.itg.extjstest.domain.Employee;
import java.util.Date;
import java.util.Set;

privileged aspect Contract_Roo_JavaBean {
    
}
