// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.extjstest.domain;

import com.itg.extjstest.domain.Employee;

privileged aspect Employee_Roo_JavaBean {
    
    public String Employee.getName() {
        return this.name;
    }
    
    public void Employee.setName(String name) {
        this.name = name;
    }
    
}
