// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.extjstest.domain;

import com.itg.extjstest.domain.Inspection;
import com.itg.extjstest.domain.InspectionItem;
import java.util.Date;
import java.util.Set;

privileged aspect Inspection_Roo_JavaBean {
    

}
