// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.extjstest.domain;

import com.itg.extjstest.domain.MaterialDoc;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MaterialDoc_Roo_Configurable {
    
    declare @type: MaterialDoc: @Configurable;
    
}
