// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.itg.extjstest.domain;

import com.itg.extjstest.domain.Menu;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Menu_Roo_Configurable {
    
    declare @type: Menu: @Configurable;
    
}
